name: Build and Push Next Docker Image

on:
  push:
    tags:
      - 'next/*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for the Next Docker image'
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Determine version
      id: determine_version
      run: |
        if [ -z "${{ github.event.inputs.version }}" ]; then
          # 从标签名称中提取版本号（移除 'next/' 前缀）
          TAG_NAME="${{ github.ref_name }}"
          if [[ $TAG_NAME == next/* ]]; then
            EXTRACTED_VERSION="${TAG_NAME#next/}"
            echo "VERSION=$EXTRACTED_VERSION" >> $GITHUB_ENV
          else
            echo "VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV
          fi
        else
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        fi

    - name: Print version
      run: echo "Next Version is $VERSION"

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:$VERSION -f next/Dockerfile .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:$VERSION
        docker tag ghcr.io/${{ github.repository }}:$VERSION ghcr.io/${{ github.repository }}:next
        docker push ghcr.io/${{ github.repository }}:next 
